pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'mvn -f demo-cicd-app/pom.xml clean package'
      }
    }
    stage('Deploy CloudHub') {
      environment {
        ANYPOINT_CREDENTIALS = credentials('anypoint.credentials')
      }
      steps {
        sh 'mvn -f demo-cicd-app/pom.xml deploy -Danypoint.username=${ANYPOINT_CREDENTIALS_USR} -Danypoint.password=${ANYPOINT_CREDENTIALS_PSW}'
      }
    }
    
  }
}
